apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-conn-secret" (.Values.app.name | default .Release.Name) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secret.db_connection }}