apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (.Values.appName | default .Release.Name) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dotnetapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "dotnetapp.selectorLabels" . | nindent 4 }}
