app:
  name: "superbill-api"
  image: acrsuperbilldev24522.azurecr.io/superbill-api:dev-main-{APP-REPO-COMMIT-ID}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

env:
- name: ASPNETCORE_URLS
  value: "http://0.0.0.0:8080"
- name: ConnectionStrings__DefaultConnection
  valueFrom:
    secretKeyRef:
      name: superbill-conn
      key: ConnectionStrings__DefaultConnection

ingress:
  enabled: true
  className: "nginx"
  annotations: { nginx.ingress.kubernetes.io/ssl-redirect: "true" }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: superbillapid.zayniq.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  - host: superbilluid.zayniq.org
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - "superbillapid.zayniq.org"
    - "superbilluid.zayniq.org"
    secretName: superbill-tls
